name: License Scan  # Nom du workflow

on:
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  license-check:
    runs-on: ubuntu-latest  # Exécute sur une machine Ubuntu

    permissions:
      checks: write
      contents: read

    steps:
      # 1️⃣ Télécharge le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Choisis la version Python

      # 3️⃣ Installe les dépendances (à partir de requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4️⃣ Installe pip-licenses pour scanner les licences
      - name: Install pip-licenses
        run: pip install pip-licenses

      # 5️⃣ Génère un rapport des licences
      - name: Generate license report
        run: |
          pip-licenses --format=json --output-file license_report.json
          pip-licenses --format=plain-vertical --with-license-file > license_report.txt

      # 6️⃣ Sauvegarde le rapport en tant qu’artefact
      - name: Upload License Report
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: |
            license_report.json
            license_report.txt
